versions:
  "1.2.0":
    folder: "binary"
  "1.2.0-alpha.1":
    folder: "binary"
  "1.1.2":
    folder: "binary"
  "1.1.0":
    folder: "binary"
  "1.0.2":
    folder: "binary"
  "1.0.1":
    folder: "binary"
