versions:
  "3.6.7":
    folder: all
  "3.6.6":
    folder: all
  "3.6.5":
    folder: all
  "3.6.4":
    folder: all
  "3.6.3":
    folder: all
  "3.6.2":
    folder: all
  "3.6.1":
    folder: all
  "3.6.0":
    folder: all
